import React from 'react';
import { ShieldCheck, Scale, Database, Lock, AlertTriangle, BookOpen, Layers, RefreshCw } from 'lucide-react';

export default function AboutPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-12">
      
      {/* Header */}
      <div className="text-center space-y-3 pb-6 border-b border-slate-200">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 border border-blue-200 text-blue-800 text-xs font-semibold">
          <ShieldCheck className="w-4 h-4 text-blue-600" />
          Technical Transparency & Legal Ethics
        </div>
        <h1 className="text-3xl sm:text-4xl font-bold text-slate-900 legal-heading">
          Methodology, Grounding & Legal Boundaries
        </h1>
        <p className="text-sm text-slate-600 max-w-2xl mx-auto leading-relaxed">
          How LawForce combines Retrieval-Augmented Generation (RAG), strict statutory grounding, and ethical AI standards to assist legal research in Pakistan.
        </p>
      </div>

      {/* RAG in Plain Language */}
      <section className="bg-white p-6 sm:p-8 rounded-2xl border border-slate-200 shadow-xs space-y-4">
        <div className="flex items-center gap-2.5 text-blue-700 font-bold text-lg">
          <Layers className="w-5 h-5" />
          <h2>What is RAG (Retrieval-Augmented Generation)?</h2>
        </div>
        <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
          Standard general-purpose AI language models often generate plausible-sounding but fictional legal citations, non-existent sections, or outdated precedents (a phenomenon called <em>hallucination</em>).
        </p>
        <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
          <strong>LawForce solves this problem using RAG:</strong>
        </p>
        <ol className="list-decimal list-inside space-y-2 text-xs sm:text-sm text-slate-700 pl-2">
          <li><strong>Targeted Retrieval:</strong> When you ask a question, LawForce first queries its verified 500-PDF database using hybrid semantic and exact keyword search to pull the exact statutory provisions.</li>
          <li><strong>Strict Evidence Injection:</strong> Only the retrieved legal provisions are fed to the Groq LLM.</li>
          <li><strong>Grounded Synthesis:</strong> The model is strictly instructed to explain the answer derived exclusively from that supplied legal text, attaching exact official citations.</li>
          <li><strong>Refusal Guardrail:</strong> If no matching provision is found, LawForce clearly states that the database does not contain sufficient reliable provisions on the topic.</li>
        </ol>
      </section>

      {/* Mandatory Legal Disclaimer */}
      <section className="bg-amber-50/80 p-6 sm:p-8 rounded-2xl border border-amber-200 space-y-4">
        <div className="flex items-center gap-2.5 text-amber-900 font-bold text-lg">
          <AlertTriangle className="w-5 h-5 text-amber-700" />
          <h2>Non-Advocate Legal Disclaimer</h2>
        </div>
        <div className="space-y-3 text-xs sm:text-sm text-amber-900/90 leading-relaxed">
          <p>
            <strong>LawForce is a legal research and informational tool, NOT a licensed Pakistani advocate, law firm, or substitute for formal legal representation.</strong>
          </p>
          <p>
            The information generated by this tool is for educational and research purposes only. The laws of Pakistan are subject to ongoing amendments, notifications, judicial interpretation, and territorial nuances.
          </p>
          <ul className="list-disc list-inside space-y-1.5 pl-2 font-medium">
            <li>No Advocate-Client Relationship is created through the use of this system.</li>
            <li>Always consult a licensed Pakistani advocate for formal legal advice, filings, litigation strategy, criminal exposure, or property conveyancing.</li>
            <li>In cases of emergency or immediate threat to physical safety, contact official Pakistani emergency services immediately (Police: 15, Rescue: 1122).</li>
          </ul>
        </div>
      </section>

      {/* Corpus Scope & Integrity */}
      <section className="bg-white p-6 sm:p-8 rounded-2xl border border-slate-200 shadow-xs space-y-4">
        <div className="flex items-center gap-2.5 text-slate-900 font-bold text-lg">
          <Database className="w-5 h-5 text-blue-700" />
          <h2>Verified Corpus Scope (500 PDF Catalog)</h2>
        </div>
        <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
          The initial LawForce corpus consists of exactly <strong>500 unique, readable, and checksum-verified PDF legal documents</strong> representing:
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs pt-2">
          <div className="p-3 bg-slate-50 rounded-lg border border-slate-200">
            <strong>30 Constitutional Instruments:</strong> Constitution 1973 consolidated text + Amendments 1st through 26th.
          </div>
          <div className="p-3 bg-slate-50 rounded-lg border border-slate-200">
            <strong>180 Core Federal Acts & Ordinances:</strong> PPC 1860, CrPC 1898, CPC 1908, QSO 1984, Specific Relief, Companies Act 2017, etc.
          </div>
          <div className="p-3 bg-slate-50 rounded-lg border border-slate-200">
            <strong>60 Federal Rules & Regulations:</strong> Supreme Court Rules, High Court Rules & Orders, Tax Rules, PECA Rules.
          </div>
          <div className="p-3 bg-slate-50 rounded-lg border border-slate-200">
            <strong>200 Provincial Acts & Rules:</strong> 60 Punjab, 50 Sindh, 50 Khyber Pakhtunkhwa, and 40 Balochistan statutes.
          </div>
          <div className="p-3 bg-slate-50 rounded-lg border border-slate-200 sm:col-span-2">
            <strong>30 Reported Precedents:</strong> 20 Supreme Court Landmark judgments + 10 High Court reported decisions.
          </div>
        </div>
      </section>

      {/* Privacy & Updates */}
      <section className="bg-white p-6 sm:p-8 rounded-2xl border border-slate-200 shadow-xs space-y-4">
        <div className="flex items-center gap-2.5 text-slate-900 font-bold text-lg">
          <Lock className="w-5 h-5 text-blue-700" />
          <h2>Privacy, Security & Maintenance</h2>
        </div>
        <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
          <strong>Data Privacy:</strong> Queries are processed without storing personally identifiable information. Supabase Auth handles authentication credentials with industry-standard cryptographic token security.
        </p>
        <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
          <strong>Continuous Maintenance:</strong> Automated verification runs ensure every document is matched against its official SHA-256 hash. When new statutory amendments are gazetted, versioned entries are created without deleting historical legislative records.
        </p>
      </section>

    </div>
  );
}
